# Generated by Django 4.1.1 on 2022-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.CharField(max_length=20)),
                ('E_name', models.CharField(max_length=100)),
                ('E_email', models.EmailField(max_length=254)),
                ('E_contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee_crud',
            },
        ),
    ]
